services:
  - type: web
    name: ai-service
    env: docker
    plan: free

    envVars:
      - key: PORT
        value: 8000       
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
